### ISSUE TITLE
Can't open settings GUI without the Internet connection

### ISSUE THREAD

**Issue by ZekerZhayard** [ChatTriggers/ChatTriggers#182]
**Describe the bug**
Can't open settings GUI without the Internet connection.

**To Reproduce**
1. Delete the `.minecraft/config/ChatTriggers` folder.
2. Disable the internet connection or use an invalid proxy server.
3. Launch game.
4. Run `/ct settings`

**Expected behavior**
The Minecraft window would freeze for a while, and the settings GUI would not be opened.

**Setup (please complete the following information):**
 - OS: Windows
 - ChatTriggers Version: 1.1.2
 - Minecraft Version: 1.8.9
- Java Version: 1.8.0_241

**Additional context**
```
[13:54:42] [Client thread/INFO]: [CHAT] An unknown error occurred while attempting to perform this command
[13:54:42] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: java.lang.ExceptionInInitializerError
[13:54:42] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at com.chattriggers.ctjs.utils.config.GuiConfig.<init>(GuiConfig.kt:13)
[13:54:42] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at com.chattriggers.ctjs.commands.CTCommand.run(CTCommand.kt:75)
[13:54:42] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at com.chattriggers.ctjs.commands.CTCommand.func_71515_b(CTCommand.kt:49)
[13:54:42] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at net.minecraftforge.client.ClientCommandHandler.func_71556_a(ClientCommandHandler.java:72)
[13:54:42] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at net.minecraft.client.gui.GuiScreen.func_175281_b(GuiScreen.java:446)
[13:54:42] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at net.minecraft.client.gui.GuiScreen.func_175275_f(GuiScreen.java:437)
[13:54:42] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at net.optifine.gui.GuiChatOF.func_175275_f(GuiChatOF.java:41)
[13:54:42] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at net.minecraft.client.gui.GuiChat.func_73869_a(GuiChat.java:111)
[13:54:42] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:578)
[13:54:42] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:534)
[13:54:42] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
[13:54:42] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
[13:54:42] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
[13:54:42] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at net.minecraft.client.main.Main.main(SourceFile:124)
[13:54:42] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:54:42] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:54:42] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:54:42] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at java.lang.reflect.Method.invoke(Method.java:498)
[13:54:42] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[13:54:42] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[13:54:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: Caused by: java.net.SocketException: Can't connect to SOCKS proxy:Connection refused: connect
[13:54:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]:    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:428)
[13:54:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]:    at java.net.Socket.connect(Socket.java:606)
[13:54:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]:    at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
[13:54:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]:    at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
[13:54:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]:    at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[13:54:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]:    at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
[13:54:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]:    at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
[13:54:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]:    at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[13:54:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]:    at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
[13:54:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]:    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:200)
[13:54:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]:    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181)
[13:54:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]:    at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1046)
[13:54:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]:    at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1044)
[13:54:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]:    at java.security.AccessController.doPrivileged(Native Method)
[13:54:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]:    at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784)
[13:54:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]:    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1043)
[13:54:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]:    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[13:54:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]:    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
[13:54:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]:    at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:92)
[13:54:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]:    at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1490)
[13:54:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]:    at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1488)
[13:54:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]:    at java.security.AccessController.doPrivileged(Native Method)
[13:54:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]:    at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784)
[13:54:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]:    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1487)
[13:54:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]:    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
[13:54:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]:    at com.chattriggers.ctjs.minecraft.libs.renderer.Image$Companion.getBufferedImage(Image.kt:85)
[13:54:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]:    at com.chattriggers.ctjs.minecraft.libs.renderer.Image$Companion.access$getBufferedImage(Image.kt:71)
[13:54:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]:    at com.chattriggers.ctjs.minecraft.libs.renderer.Image.<init>(Image.kt:26)
[13:54:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]:    at com.chattriggers.ctjs.utils.config.IconHandler.<clinit>(IconHandler.kt:16)
[13:54:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]:    ... 20 more
```

```
[14:00:30] [Client thread/INFO]: [CHAT] An unknown error occurred while attempting to perform this command
[14:00:30] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: java.lang.NoClassDefFoundError: Could not initialize class com.chattriggers.ctjs.utils.config.IconHandler
[14:00:30] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at com.chattriggers.ctjs.utils.config.GuiConfig.<init>(GuiConfig.kt:13)
[14:00:30] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at com.chattriggers.ctjs.commands.CTCommand.run(CTCommand.kt:75)
[14:00:30] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at com.chattriggers.ctjs.commands.CTCommand.func_71515_b(CTCommand.kt:49)
[14:00:30] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at net.minecraftforge.client.ClientCommandHandler.func_71556_a(ClientCommandHandler.java:72)
[14:00:30] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at net.minecraft.client.gui.GuiScreen.func_175281_b(GuiScreen.java:446)
[14:00:30] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at net.minecraft.client.gui.GuiScreen.func_175275_f(GuiScreen.java:437)
[14:00:30] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at net.optifine.gui.GuiChatOF.func_175275_f(GuiChatOF.java:41)
[14:00:30] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at net.minecraft.client.gui.GuiChat.func_73869_a(GuiChat.java:111)
[14:00:30] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:578)
[14:00:30] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:534)
[14:00:30] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
[14:00:30] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
[14:00:30] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
[14:00:30] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at net.minecraft.client.main.Main.main(SourceFile:124)
[14:00:30] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:00:30] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:00:30] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:00:30] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at java.lang.reflect.Method.invoke(Method.java:498)
[14:00:30] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[14:00:30] [Client thread/INFO] [STDERR]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]:     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by mattco98** [comment]
Fixed in 91a9a46cfe6bd328969e2fa7ec9e650aef1d4c0d - thanks for the report!
