### ISSUE TITLE
"Found an old version of ASM (5.0.3)", and it never launches

### ISSUE THREAD

**Issue by zodiia** [ChatTriggers/ChatTriggers#345]
I unfortunately cannot use ChatTriggers anymore, as it constantly crashes when attempting to start the game.

The following message keeps showing up: "Found an old version of ASM (5.0.3). This may cause issues.". It also says that it will attempt "relauching", whatever it means. Then the game crashes with this error:
```
Mixin prepare failed preparing compatibility.labymod.MixinCustomMainMenu in mixins.essential.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException java.lang.ArrayIndexOutOfBoundsException: 6
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: java.lang.ArrayIndexOutOfBoundsException: 6
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:885)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:850)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:775)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:539)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.launcher.FMLDeobfTweaker.injectIntoClassLoader(FMLDeobfTweaker.java:34)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124)
	at gg.essential.loader.stage2.EssentialLoader.preloadEssential(EssentialLoader.java:145)
	at gg.essential.loader.stage2.EssentialLoader.loadPlatform(EssentialLoader.java:91)
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:110)
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53)
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 6
	at org.objectweb.asm.ClassReader.readShort(ClassReader.java:2403)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:184)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:168)
	at net.minecraftforge.fml.common.asm.transformers.DeobfuscationTransformer.transform(DeobfuscationTransformer.java:41)
	at org.spongepowered.asm.service.mojang.LegacyTransformerHandle.transformClassBytes(LegacyTransformerHandle.java:80)
	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.applyTransformers(MixinServiceLaunchWrapper.java:548)
	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.getClassBytes(MixinServiceLaunchWrapper.java:514)
	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.getClassNode(MixinServiceLaunchWrapper.java:592)
	at gg.essential.mixins.Plugin.hasClass(Plugin.java:98)
	at gg.essential.mixins.Plugin.shouldApplyMixin(Plugin.java:67)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.shouldApplyMixin(PluginHandle.java:132)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.shouldApplyMixin(MixinInfo.java:987)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:952)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:881)
	... 45 more
```

Unfortunately, this message isn't documented anywhere, and I couldn't find where is located the library to remove it and/or update it myself.

Downgrading to an older version didn't work.

It also seems to be conflicting with Optifine, as the error goes away when I disable Optifine.

**Comment by camnwalter** [comment]
This seems like an Essential problem.  Join their discord (discord.gg/essential) and open up a ticket in the #support channel.  Someone there should help you fix this.

**Comment by U5B** [comment]
Just another note: I don't think LabyMod is supported with Essential but I could be wrong.

**Comment by SystemlessDev** [comment]
Send the full log please. That snippet doesn't mean much. A wild assumption says that you're either using a version of OptiFine before I7, or you're using a unofficial version (from f.ex. tlauncher or HMCL) 

To maintainers: you guys can close this issue. It's not related to ctjs at all (obviously). 

Essential will always log that it finds a old version of ASM since we upgrade ASM so that we can also upgrade mixin. Relaunching is a part of this procedure. 

Either way you should get in contact with us in our discord server as squagward said (discord.gg/essential)
