### ISSUE TITLE
Unable to import any modules

### ISSUE THREAD

**Issue by Katchowski** [ChatTriggers/ChatTriggers#397]
**Describe the bug**
"/ct import Coleweight" and "/ct import HypixelAutocomplete" both resulted in the following error message

javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1479)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivileged(AccessController.java:713)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at com.chattriggers.ctjs.engine.module.ModuleUpdater.downloadModule(ModuleUpdater.kt:142)
	at com.chattriggers.ctjs.engine.module.ModuleUpdater.importModule(ModuleUpdater.kt:114)
	at com.chattriggers.ctjs.engine.module.ModuleUpdater.importModule$default(ModuleUpdater.kt:100)
	at com.chattriggers.ctjs.engine.module.ModuleManager.importModule(ModuleManager.kt:177)
	at com.chattriggers.ctjs.commands.CTCommand$import$2.invoke(CTCommand.kt:89)
	at com.chattriggers.ctjs.commands.CTCommand$import$2.invoke(CTCommand.kt:88)
	at com.chattriggers.ctjs.Reference$conditionalThread$1.invoke(Reference.kt:108)
	at com.chattriggers.ctjs.Reference$conditionalThread$1.invoke(Reference.kt:106)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
	... 32 more

**To Reproduce**

Unknown

**Expected behavior**

I just want coleweight

**Setup (please complete the following information):**
 - OS: Win 11
 - ChatTriggers Version: 2.2.0
 - Minecraft Version: 1.8.9
- Java Version: build 1.8.0_401-b10

**Additional context**

Attempted on both a VPN and non-VPN connection.

**Comment by camnwalter** [comment]
You can follow the guide here: https://github.com/ChatTriggers/ChatTriggers/wiki/Fixing-broken-imports. If you still have questions please feel free to ask in our [Discord](discord.gg/chattriggers)

**Comment by Katchowski** [comment]
Thank you!
